### ISSUE TITLE
MinGW 環境でテストコードがビルドできない

### ISSUE THREAD

**Issue by progre** [plonk/peercast-yt#115]
GitHub Action で Linux 版と Windows 版のビルドにトライしています。（もし本リポでも必要であれば PR 作成します。）
https://github.com/progre/peercast-yt/tree/ci

各 OS のビルドと、Linux 版のテスト実行はできましたが、Windows 版のテストのビルドが上手くいっていません。

https://github.com/progre/peercast-yt/runs/7767729455

gtest が持つファイルが見えていないようなんですが、ローカル環境で確認するとどこにも該当のファイルがありませんでした。

Linux 版では 1.10.x を使っていて、MinGW 版では 1.12.1 を使っているので、バージョンに依存しているのでしょうか。

mingw 環境で gtest の古いバージョンを利用する方法がわからないので、今のところお手上げ状態です 🤔 。

**Comment by plonk** [comment]
手元の MSYS2 では googletest の 1.11 を使っていたのですが、1.12 にアップデートしたら確かに gtest-all.cc がなくなりました。意図的なことなのかパッケージャーの人のミスなのかわかりませんが…。ともあれ、gtest-all.cc の代わりに libgtest をリンクすれば良いようです。

```
diff --git a/ui/mingui/tests/Makefile b/ui/mingui/tests/Makefile
index 3086658..6a6b0b5 100644
--- a/ui/mingui/tests/Makefile
+++ b/ui/mingui/tests/Makefile
@@ -27,6 +27,7 @@ CXXFLAGS += -g -Wno-multichar -Wno-unused-variable -std=c++11

 LDFLAGS =
 LIBS = -lwinpthread -lws2_32 -lShlwapi $(shell pkg-config librtmp --libs) $(shell pkg-config openssl --libs)
+LIBS += -lgtest

 # All tests produced by this Makefile.  Remember to add new tests you
 # created to the list.
@@ -78,5 +79,5 @@ OBJS = $(notdir $(SRC:.cpp=.o))
 $(OBJS): %.o : ../../../tests/%.cpp $(wildcard $(USER_DIR)/*.h) $(GTEST_HEADERS)
        $(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $<

-test-all : $(OBJS) ../libpeercast.a gtest.a
+test-all : $(OBJS) ../libpeercast.a
        $(CXX) $(LDFLAGS) $^ -o $@ $(LIBS)
```

**Comment by progre** [comment]
ありがとうございます！ビルドできました。

**Comment by progre** [comment]
万事うまくいきました 😎
https://github.com/progre/peercast-yt/runs/7930180200
