### ISSUE TITLE
配信を開くとコンタクトURLに[object Object]と自動的に投稿される

### ISSUE THREAD

**Issue by nurburgringnord** [plonk/peercast-yt#122]
windows11
x64版 バージョンyt46

件名の通り、配信を開くとコンタクトURLに自動的に「[object Object]」と自動的に投稿されます。
peercast yt再起動、PC再起動でも再現します。
防止策があればお教えいただきたく思います。

**Comment by plonk** [comment]
HTML UI のチャンネルリストからチャンネルを選んで、ブラウザ内で再生する場合の話ですよね？
Windows 10 の Chrome と Firefox で試してみたのですが再現しませんでした。

お使いのブラウザは何ですか？　ブラウザを変えても [object Object] と自動的に投稿されますか？

**Comment by nurburgringnord** [comment]
ブラウザはvivaldiを使用しております
chromeで再生してみたところ、自動的に投稿されませんでした。

**Comment by nurburgringnord** [comment]
vivaldiのアップデートにより修正されたようです
お手数をおかけし、申し訳ありませんでした
ありがとうございました！
