### ISSUE TITLE
RTSPの定数が残ってる

### ISSUE THREAD

**Issue by shinji3** [plonk/peercast-yt#16]
最近のコミットでRTSPを削除したようですが、
http.hにRTSP_SC_OKとRTSP_PROTO1と
servent.hにhandshakePOST()が残ってます
それは削除しないのでしょうか？

**Comment by plonk** [comment]
定数を削除しました。https://github.com/plonk/peercast-yt/commit/6aa7d199df328501d5a388f477ceb130de1edb10
handshakePOST は HTTP POST の処理に転用したので残します。

**Comment by shinji3** [comment]
handshakePOST()とhandshakePOST(HTTP &http)がありますが
handshakePOST()の方は使ってないような

**Comment by plonk** [comment]
なるほど。削除しました。https://github.com/plonk/peercast-yt/commit/00dfa1458dc5fc3d7b307406910a1b2dbaf6b410
