### ISSUE TITLE
VisualStudioでビルドすると出た警告

### ISSUE THREAD

**Issue by shinji3** [plonk/peercast-yt#31]
何か開発の参考になればと思い書きます

sys.hにある
typedef unsigned int THREAD_HANDLE;

のままVisualStudioを使って64bitでビルドすると下のような警告が出るので
warning C4312: '型キャスト': 'THREAD_HANDLE' からより大きいサイズの 'void *' へ変換します。
warning C4244: '=': 'uintptr_t' から 'THREAD_HANDLE' への変換です。データが失われる可能性があります。

typedef uintptr_t THREAD_HANDLE;
にした方が良いと思います。IMでもそうなってました

cgi.cppにあるrfc1123Time関数ですが
ptm = gmtime(&t);
だとVisualStudioで
warning C4996: 'gmtime': This function or variable may be unsafe. Consider using gmtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
と警告がでるのでgmtimeを使うよりもgmtime_sを使った方が良いと思います。引数もgmtime_rを反対にしただけですし
gmtime_r(&t, &tm);がこうだとしたらgmtime_s(&tm, &t);はこんな感じに使えます

windows.hをインクルードするとstd::minとstd::maxの名前が衝突してしまいます
std::min()は(std::min)()でstd::max()は(std::max)()と書くと名前が衝突しないみたいです
解決方法の一つの#define NOMINMAXのやり方は他のwindows.hのminとmaxを使うヘッダーをインクルードするとエラーになるのでNOMINMAXは使わない方が良さそうです

sstream.cppにあるStringStream::readなんですが
VisualStudioを使って64bitのDebugでビルドすると下のような警告が出るので
warning C4996: 'std::copy::_Unchecked_iterators::_Deprecate': Call to 'std::copy' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
'std::copy::_Unchecked_iterators::_Deprecate' の宣言を確認してください
コンパイル対象の関数 テンプレート インスタンス化 '_OutIt *std::copy<std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,char*>(_InIt,_InIt,_OutIt)' のリファレンスを確認してください
1>        with
1>        [
1>            _OutIt=char *,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>
1>        ]
warning C4244: 'return': '__int64' から 'int' への変換です。データが失われる可能性があります。

こんな感じに書き直したのですがどうでしょうか？
    int  StringStream::read(void *buf, int count)
    {
        if (m_pos == m_buffer.size())
            throw StreamException("End of stream");
        int bytesRead = (std::min)(count, static_cast<int>(m_buffer.size() - m_pos));
        memcpy(buf, m_buffer.c_str() + m_pos, bytesRead);;
        m_pos += bytesRead;
        return bytesRead;
    }

stricmpを使うと
warning C4996: 'stricmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _stricmp. See online help for details.
とVisualStudioに出るので_stricmpに書き直してはどうでしょうか？

他にもfopenを使うとfopen_sとか
ctimeをctime_sとか
VisualStudioで警告が出ました

**Comment by plonk** [comment]
これって YT15 を MinGW に移植したブランチでしょうか？
(YT16 以降 Windows には無い API を使っているので…)
VisualStudio でビルドできましたか？

**Comment by shinji3** [comment]
最新のmasterです。取りあえず警告はまだですがエラーは直しました
https://github.com/shinji3/peercast-yt

**Comment by shinji3** [comment]
corelibだけですが警告もエラーも0にしました
https://github.com/shinji3/peercast-yt

**Comment by shinji3** [comment]
peercast-ytをGUI付きでビルド出来ました
https://github.com/shinji3/peercast-yt

**Comment by shinji3** [comment]
peercast-ytの更新を取り込んだらcgiが動くようになりました。ありがとうございます。
でも、こっちのVisualStudioでビルドしたのはCGIが動く時に黒いウィンドウが出たりしますけど出なくすること出来ますかね？
あとそれとflv.jsが更新されていますよ

**Comment by shinji3** [comment]
黒いウィンドウの問題はCreateProcess関数にCREATE_NO_WINDOWを付けたら解決しました

**Comment by shinji3** [comment]
cstream.hのMAX_DATALEN = 16384が大きすぎてChanPacket packets[MAX_PACKETS];
とか使うとVisualStudioのデバッグ実行でエラーになりました。
取りあえず私はMAX_DATALEN = 12288にしています。

**Comment by shinji3** [comment]
MAX_DATALENを小さくするとFLV配信が見れなくなったのでMAX_DATALENの代わりに
cstream.hのMAX_PACKETSを小さくするとFLV配信も見れてデバッグ実行でもエラーにならず良さげです

**Comment by plonk** [comment]
どういったエラーでしょうか？ IDE で内容を表示するには大きすぎるとか？

伝統的に PeerCast の実装では最大パケットサイズは 16KB、バッファーのパケット数は 64 になっていて、これに合わせて配信されるパケットサイズや送出速度が制御されているので、これらの定数をいたずらに変更することはできません。

**Comment by shinji3** [comment]
MAX_PACKETSはNUM_SAFEPACKETSと同じ値を使ったからいけるような気もしましたが、
そうなんですね。分かりました。ちなみにgtestのエラーです
unknown file: error: SEH exception with code 0xc00000fd thrown in the test body.
[  FAILED  ] ChanHitFixture.initLocal (1 ms)
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] ChannelFixture.initialState (0 ms)
VisualStudioのエラーはこんな感じです
0x00007FF73BF80418 で例外がスローされました (tests.exe 内): 0xC0000005: 場所 0x000000691D020000 への書き込み中にアクセス違反が発生しました

**Comment by shinji3** [comment]
ちなみにIMにはChanPacketのメモリを動的に使う版のChanPacketvがあるみたいなんで
エラーを直すのにそれが参考になるかもしれません。
あと下のページのPeerCast.slnでエラーが出るか試すことが出来ます
https://github.com/shinji3/peercast-yt

**Comment by shinji3** [comment]
ちなみにパケットサイズは変更するとFLV配信の再生に影響しましたが、
試しにパケット数を少なくして見ましたが今のところは再生に問題は無いです
パケット数は弄っても問題ない気がするような

**Comment by plonk** [comment]
上流からパケット受け取るスレッドと、下流へパケットを流すスレッドは別々で、後者はパケットバッファーの状態をポーリングしています。したがって、バッファーに蓄えられるパケット数は、パケットの取りこぼし（スキップ）を起こさずにリレーできるパケットレートの上限に関係します。

パケットレートは配信ビットレートに応じて高くなるので、結局、パケット数はリレーできる最大ビットレートに影響することになります。パケット数を減らしても、例えば WMV や FLV で10Mbpsのリレーができるなら、実質「問題ない」と言えるでしょうが、正常動作のマージンを減らすことにはなります。

**Comment by shinji3** [comment]
ChanPacketvを追加してMAX_PACKETS = 64に戻したらエラーは無くなりました
https://github.com/shinji3/peercast-yt/commit/613cf03d90c707d528e825cba70bd2c54b8df473

**Comment by plonk** [comment]
一体なんのエラーか未だにわかりませんが＾＾；

**Comment by shinji3** [comment]
cstream.hにあるNUM_SAFEPACKETSの話なんですが
IMではNUM_SAFEPACKETS = 60になってますけど
YTではNUM_SAFEPACKETS = 56になってます
これはリレーに影響はしないのでしょうか？

**Comment by plonk** [comment]
把握していません。

**Comment by shinji3** [comment]
WindowsでCGIを動作させる良いRubyを見つけました
http://jruby.org/download

上のURLのJRuby 9.1.12.0 Complete .jarと言う1ファイルで動作するRubyです
それをjruby-complete.jarにリネームしてPeerCast.exeと同じフォルダに置きます
subprog.cppにある
(char*) ("ruby \"" + m_name + "\"").c_str()
になっている所を
(char*) ("java -jar jruby-complete.jar \"" + m_name + "\"").c_str()
に変更するとRubyがインストールされて無くてもJavaがあれば動作します

**Comment by plonk** [comment]
なるほど。JRubyを使うという発想はありませんでした。

そもそもCGIスクリプトをC++で書き直してしまえば、環境を選ばないのですが、めんどうだなぁ…。

**Comment by shinji3** [comment]
rubyでは無くpythonで書き直せば解決すると思います

pythonだと公式で最小限の Python 環境を含んだ ZIP ファイルが配布されているので
https://www.python.org/downloads/windows/

公式のドキュメント　Python 埋め込みのための配布
https://docs.python.jp/3/using/windows.html#embedded-distribution

あとjythonも試してみましたがjrubyと同じく起動にCPUを食って実用的じゃありませんでした

**Comment by shinji3** [comment]
試しにrubyからpythonに移植して見ました。どうでしょうか？
https://github.com/shinji3/peercast-yt/tree/master/ui/linux/cgi-bin
https://github.com/shinji3/peercast-yt/commit/756915adae16a16326b1616daed7c476b884a60e

**Comment by plonk** [comment]
取り込みましょうか？ プルリクエストしていただければ、多分取り込みます。

**Comment by peer1234** [comment]
YTだかなんだかしらんがいい加減宣伝うぜえ
ピアキャススレ荒らすのやめろ

**Comment by shinji3** [comment]
PeerCastの配信をブラウザで見る良い方法を考えました
InternetExplorerしか見れませんがFLV(H264+AAC or MP3)配信をWMV(H264+AAC or MP3)配信に変換してWMP Pluginで見るという方法です
エンコードせずにフォーマットしか変換してないのでWMVをFLVに変換するより圧倒的に軽いです
たぶんWMV Codec Packを導入すればWMP PluginでもWMV(H264+AAC or MP3)配信を見れると思います
WMV配信はそのままでFLV配信はWMV(H264+AAC or MP3)配信に変換して見ればブラウザでも使いやすいと思います
なぜFlash PlayerがあるのにWMV(H264+AAC or MP3)配信に変換するのかと言うと
flv.jsはInternetExplorerでは使えないのでFLV配信はFlashPlayerで見るしか無いのですが
FlashPlayerでhttpのまま見るとキャッシュが溜まってしまうからです
それにWMVもFLVも同じUIで使えるのが理由ですね

もしくはWMV(H264+AAC)を流行らせてflv.jsのWMV版のwmv.jsを作るとかですね
flv.jsのflv demuxerをwmv demuxerに変えればいけると思います
MMSHはhttpと互換性があるからいけると思うのですがどうでしょうか？

**Comment by plonk** [comment]
MMSH をブラウザで実装することの妥当性については全然わかりません！
もし難しければ、ペカステのように通常のHTTP要求でWMVストリームが流れるように本体側を変更することはできます。
ただ、目的が H264 WMV を再エンコードなしにブラウザで再生することなら、ffmpeg を利用してサーバーサイドでFLVに詰め直す方法もあるんではないでしょうか。

**Comment by shinji3** [comment]
確かにそういう方法もありますね。
ところでffmpegをjavascriptに変換したvideoconverter.jsとかidleencoderとかがあるようです。
最近はWebAssemblyがあるのでMMSH をブラウザで実装出来れば
コーデックが違っても対応形式にエンコードしながら再生とか出来るかも知れません。難しそうですが

**Comment by shinji3** [comment]
flv.cgiがrubyだったのでpython3で書き直しました
https://github.com/shinji3/peercast-yt/blob/master/ui/linux/cgi-bin/flv.cgi

**Comment by plonk** [comment]
取り込みました。ありがとうございます。

**Comment by shinji3** [comment]
rtmp.cppの#define MAX_PACKET_SIZE (1024*1024)だと値が大きすぎてエラーになりましたが
#define MAX_PACKET_SIZE (512*1024)だと上手く行きました。
あとflv.js が v1.3.2にバージョンアップしました

**Comment by shinji3** [comment]
ChanPacketとRTMPのエラーは、スタックオーバーフローが原因みたいです。
巨大な配列をスタックに配置した場合の所に書いてます
https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%BF%E3%83%83%E3%82%AF%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%95%E3%83%AD%E3%83%BC

**Comment by shinji3** [comment]
channel.cppの
MemoryStream mem(pack.data, sizeof(pack));
は
MemoryStream mem(pack.data, sizeof(pack.data));
が正しいような気がするんですがどうなんでしょうか？
https://github.com/shinji3/peercast-yt/commit/65a0d6adacb3a3d6b2e23cec5267406571b14b1b

**Comment by plonk** [comment]
FLVパケットを読み込むバッファーをヒープに取るようにしました。 https://github.com/plonk/peercast-yt/commit/332839b2a8783a8a0912d4e88ee60a90e8b89294

> channel.cppの
> MemoryStream mem(pack.data, sizeof(pack));
> は
> MemoryStream mem(pack.data, sizeof(pack.data));
> が正しいような気がするんですがどうなんでしょうか？
> shinji3/peercast-yt@65a0d6a

そのようです。取り込ませていただきました。

**Comment by shinji3** [comment]
servhs.cppのServent::handshakePLSにあるchar in[128];は使われていないみたいです
VisualStudioだとgnuid.cppとstream.hに#include <algorithm>が必要みたいです

**Comment by plonk** [comment]
57fa2b6b9e627a0df8b7f311d4d6eb284744b1f8 と 857d66ce2e4c64467eddaffe53e45e8c92a4bef6 を取り込ませていただきました。

**Comment by shinji3** [comment]
strncpyですが終端文字から考えて、こうした方が正しいと思うのですがどうでしょうか？

gnutella.cppにある

	strncpy(agentStr, ag, 16);
	agentStr[15]=0;

を

	strncpy(agentStr, ag, 15);
	agentStr[15]=0;

に変更


sys.cppにある

	strncpy(dest, src, destsize);
	dest[destsize - 1] = '\0';

を

	strncpy(dest, src, destsize - 1);
	dest[destsize - 1] = '\0';

に変更


http.cppにある

	strncpy(user, str.cstr(), ulen);
	user[ulen - 1] = 0;

を

	strncpy(user, str.cstr(), ulen - 1);
	user[ulen - 1] = 0;

に

	strncpy(pass, s+1, plen);
	pass[plen - 1] = 0;

を

	strncpy(pass, s+1, plen - 1);
	pass[plen - 1] = 0;

に変更

**Comment by plonk** [comment]
結果は同じですよね？　strncpy は '\0' を書き込むサイズがバッファーにない場合でもオーバーランはしないので、元の書き方でも正しいです。

**Comment by shinji3** [comment]
そうですか。元の書き方の場合strncpyの時に1バイト無駄なコピーが発生するので、
その分、効率が悪くなるような気がしたので

**Comment by plonk** [comment]
無駄なコピーが節約できるのは、コピー元の文字列の長さがバッファーサイズ - 1 以上の場合だけですよね。バッファーに余裕を持って収まる文字列をコピーするときには、strncpy 内での計算量は変わらず、むしろ呼び出し元での計算量が増えるのではありませんか？

そもそも、strncpy の計算量を下げると YT 自体の性能に有意な向上がありますか？ この関数が実行されている時間は全体の 1% にも満たないのではありませんか？

**Comment by shinji3** [comment]
そうですね。試しにベンチを取って見ましたがほぼ同じでした。
strncpyだとVisualStudioでワーニングが出るので

他のstrncpyはこんな感じになってるのに

	strncpy(s1, s2, sizeof(s1)-1);
	s1[sizeof(s1)-1]=0;

上のstrncpyはこんな感じになっていたので

	strncpy(s1, s2, sizeof(s1));
	s1[sizeof(s1)-1]=0;

strncpyをstrncpy_sに変更するときに少し混乱したので予定地さんに言ってみただけで
別に変なこだわりとかあるわけではありません

あと話は変わりますが上の方でも書いてますが#include \<algorithm\>してもstd::minとstd::maxが
windows.hのmin/maxマクロと衝突してVisualStudioでビルドするときにエラーになるみたいです
私は下のURLの回避策3：プリプロセッサによるマクロ展開を抑止する(1)で回避してます
http://d.hatena.ne.jp/yohhoy/20120115/p1

**Comment by shinji3** [comment]
YTにVPのUPNPを使ったポート解放機能を付けたのですがどうでしょうか？
自分のルーターしか試してないので他の環境では失敗するかも知れませんが

VP 0026+upnpのソースを移植しました
http://vols.s57.xrea.com/

バイナリです
https://github.com/shinji3/peercast-yt/releases

**Comment by plonk** [comment]
[パッチ](https://github.com/shinji3/peercast-yt/pull/3)を拝見したのですが、Linux で動く実装がないようですね。

Linux 版で動く実装があって、HTML UI から制御できるならば取り込めないことはないのですが…。

**Comment by shinji3** [comment]
upnpのライブラリを探して見たのですがminiupnpが良さそうです
libupnpはビルドするのにpthreadsが必要みたいなので
https://github.com/miniupnp/miniupnp

**Comment by shinji3** [comment]
std::threadを使うYTをVisualStudioでビルドしたらYTが起動しなくなりました
このコミットを適用しなければYTは起動はするけど、うまく動いてない感じです
https://github.com/plonk/peercast-yt/commit/c08ca92b1046d6d779c7b57c5e50e1bea12d470e

**Comment by plonk** [comment]
原因がコードにあるのか、コンパイラのC++11サポートの程度によるのか判りますか？

**Comment by shinji3** [comment]
sys.cppをこんな感じにすればちゃんと動きました
https://github.com/shinji3/peercast-yt/commit/15e74e4c3f7e85de008068808481c76a82e24d08

**Comment by shinji3** [comment]
こんな感じのコードでも動きました
https://github.com/shinji3/peercast-yt/commit/1f53a190cbb70dbe4a2460634d17aa354ccda64e

どうやら原因はこの部分みたいです

	info->handle = std::thread([info, &childBlocker, &parentBlocker]()
	                           {
	                               childBlocker.lock();    // wait til info is setup
	                               parentBlocker.unlock(); // allow parent to return
	                               info->func(info);
	                           });

**Comment by plonk** [comment]
info->nativeHandle が設定される前に info->func が走りだすと、新スレッドが Sys::setThreadName を呼び出して落ちるのですよね。（Win32では setThreadName が実装されていないので関係ないのですが）

スレッドに名前を付けるにはネイティブハンドルを取得する必要があるのですが、スレッドがデタッチされると取得できないので、デタッチする前にネイティブハンドルを保存しようとしています。

**Comment by plonk** [comment]
起動しないというは、プロセスが終了するのですか？ それともデッドロックが起きて新しいスレッドが走れない状態になっているのでしょうか？

どのバージョンのコンパイラを使ってビルドされていますか？

**Comment by shinji3** [comment]
起動するとすぐに終了するという感じです
コンパイラはVisualStudio2017のものを使ってます

**Comment by plonk** [comment]
デタッチしていないスレッドが終了するとプロセスごと終了する仕様なので、子スレッドがデタッチされる前に終了しているのでしょうか？（だとするとミューテックスでやろうとしていることが全く実現できていないことになりますが）

コンソールがあれば何かしら出力されると思うのですが…

**Comment by shinji3** [comment]
このコミットをマージしたら起動できるようになりました。ありがとうございます。
https://github.com/plonk/peercast-yt/commit/e7e01cf12ffd8921b0e3e235d30639b364b07261

**Comment by plonk** [comment]
うーん、なぜ動かなかったのかわからないので、心配です。std::mutex が正常に動作しないなら、広範囲にわたって偶発的に挙動がおかしくなる可能性がありますね。

**Comment by plonk** [comment]
特定の問題を追跡しているわけではないのでクローズします。クローズしても書き込めると思います。書き込んでいただくのは構いません。

**Comment by shinji3** [comment]
flv.jsがv1.3.3にバージョンアップしたので一応報告します

**Comment by plonk** [comment]
e8217abe7bd3255e80a4eb4faf467be9215bd68b と b789dea38480e0bbf590bbb6f8630e256ba39fc6 を取り込みました。

**Comment by shinji3** [comment]
UPnPをCOMの部分をPeerCastのAPIで実装したのですがどうでしょうか？
あとはsocketの部分をLinuxでも動くようにすればたぶんイケると思います
https://github.com/shinji3/peercast-yt/blob/master/core/win32/upnp.cpp
https://github.com/shinji3/peercast-yt/blob/master/core/win32/upnp.h

**Comment by shinji3** [comment]
onigmoがいつの間にか6.1.3にバージョンアップしたので一応報告します
