### ISSUE TITLE
FLVのMIMEタイプが間違ってます

### ISSUE THREAD

**Issue by shinji3** [plonk/peercast-yt#4]
MIME_FLVが"video/flv"になってますが"video/x-flv"が正しいと思います

**Comment by plonk** [comment]
なるほど。"video/flv" は正式に登録されたものではないんですね。
PeerCastStation も x-flv になっていますし、"video/x-flv" にしました。
0d8f30d4879b0c48ca95132c0438cb70e0cb40c8
