### ISSUE TITLE
YT12からYT25にアップデートした時のアレコレ

### ISSUE THREAD

**Issue by ha2ne2** [plonk/peercast-yt#86]
1.CSSが読み込まれない
キャッシュとクッキーなどを削除したら治りました。
（何か中身が変わったのかな・・？）

2.帯域チェック機能
YT25で作られるiniではSPとTPが帯域チェック用URLに自動で追加されるが
既存バージョンからのアップデートだとされないのがちょっと不便だった。
手動で追加してみたが帯域チェック不可となりどういう意味なのかわからなかった。
（自動でしたのでもうさせません、という意味・・？）

3.パスワードを間違えて入力した時URLに入力したパスワードが表示される
配信に映ったり等考えると、ちょっと怖い。
前のバージョンからだったと思います。

4.パスワードを間違えて入力した後に正しいパスワードでログインを試みるとリダイレクトが止まらない
デフォルトiniでChrome、Edgeで再現しました。

5.YTをYPとして外部に公開する場合、255.255.255.255にプライベートのチェックを入れる必要がある（と思う）が、そうすると自分が配信した時に全員直下になってしまう。
（プライベートにチェックを入れるとダイレクト接続が有効になる・・？プライベートとダイレクトの違いがよく分からないので説明が欲しいです。コントロール着信数上限と着信数上限も何なのか分からない。。）（今のところ自分のYTをYPとして公開する予定はないので要望希望度は低いのですが。。）

6.ピカステにある視聴していないチャンネルの自動切断機能が欲しいです。
自分の配信の直下を多くしたいのでCh毎リレー数上限を多め（5とか10とか）に設定しているのですが、
視聴していない他の配信に沢山リレーを出してたりするので、配信前に確認する必要が（自分には）あります（あまりしませんが）。
自動切断はデメリットとしてリスナー数の多い配信が不安定になる（かもしれない）という事が
考えられるので、もしそれが気になるのであれば、あるいは自分の配信だけリレー上限数を変えられるオプションが欲しいです。

以上です。更新乙です。

**Comment by plonk** [comment]
> 1.CSSが読み込まれない

偶数行、奇数行で背景色を変える処理をCSSに移しました。古いバージョンのCSSがブラウザのキャッシュにあって、それが使われたのだと思います。

> 2.帯域チェック機能
> YT25で作られるiniではSPとTPが帯域チェック用URLに自動で追加されるが
> 既存バージョンからのアップデートだとされないのがちょっと不便だった。

現在の設定ファイルのデータ形式だと、何もURLを登録していない状態と、古いバージョンだからURLがない状態を区別できないのでこうなっています。UI にデフォルトのURLを追加する機能を付けることも考えましたが、そこまでする必要があるかわからなかったので…。

> 手動で追加してみたが帯域チェック不可となりどういう意味なのかわからなかった。
> （自動でしたのでもうさせません、という意味・・？）

YP から yp4g.xml をダウンロードして、checkable=0 となっていた場合に帯域チェック不可になりますので、チェック可能かどうかを決めるのを YP 側ですが、次のような場合不可になります。

1. YP で帯域チェックサーバーが動作していない場合。（TP）
2. 前回測定時に一定以上の結果（SPでは２Mbps）が出た場合。
3. 前回の測定から一定時間が経過していない場合。

なお、自動での帯域チェックしません。

> 5.YTをYPとして外部に公開する場合、255.255.255.255にプライベートのチェックを入れる必要がある（と思う）が、そうすると自分が配信した時に全員直下になってしまう。

公開ディレクトリのことでしょうか？ 視聴URLに視聴用の認証トークンが付くので、255.255.255.255 をダイレクトやプライベートに指定する必要はありません。

YP（ルートサーバー）として動作させる場合、同じサーバーで視聴や配信をするのは上手くいかないと思います。（掲載されているチャンネルを視聴するとチャンネルが取り下げられなくなるなど）
YPを立てる場合は、別のプロセスで別のポート番号を使った方が良いです。

> 6.ピカステにある視聴していないチャンネルの自動切断機能が欲しいです。
> 自分の配信の直下を多くしたいのでCh毎リレー数上限を多め（5とか10とか）に設定しているのですが、
> 視聴していない他の配信に沢山リレーを出してたりするので、配信前に確認する必要が（自分には）あります（あまりしませんが）。
> 自動切断はデメリットとしてリスナー数の多い配信が不安定になる（かもしれない）という事が
> 考えられるので、もしそれが気になるのであれば、あるいは自分の配信だけリレー上限数を変えられるオプションが欲しいです。

チャンネルはキープしていない限りダイレクト接続が無くなった時点で切断されるようになっています。外部からダイレクト接続で視聴されている可能性はありませんか？

**Comment by ha2ne2** [comment]
> 偶数行、奇数行で背景色を変える処理をCSSに移しました。古いバージョンのCSSがブラウザのキャッシュにあって、それが使われたのだと思います。

なるほど、了解です。

> YP から yp4g.xml をダウンロードして、checkable=0 となっていた場合に帯域チェック不可になりますので、チェック可能かどうかを決めるのを YP 側ですが、次のような場合不可になります。
> YP で帯域チェックサーバーが動作していない場合。（TP）
> 前回測定時に一定以上の結果（SPでは２Mbps）が出た場合。
> 前回の測定から一定時間が経過していない場合。

そう言われるとなるほどです。一回手動でSPで測定しました。
個人的には不可だと分かりにくいかな～。。

> 公開ディレクトリのことでしょうか？ 視聴URLに視聴用の認証トークンが付くので、255.255.255.255 をダイレクトやプライベートに指定する必要はありません。

「YTをYPとして外部に公開する」というのは誰でも自分のVPSにHTTPPushで配信可能出来る状態にする、という意味でした。以前リスナーさんに試してもらったら255.255.255.255をダイレクト/プライベートにしないと出来ないっぽかったです。今は自分のIPだけ許可チェック入れてます。

>チャンネルはキープしていない限りダイレクト接続が無くなった時点で切断されるようになっています。外部からダイレクト接続で視聴されている可能性はありませんか？

あれ、すみません、これは前のバージョンでの記憶だったのですが、
今はうまく切断されます。仕様が変わったのかな。
