### ISSUE TITLE
リスナー数非表示機能を使用してチャンネルを立てると正常に作動しない

### ISSUE THREAD

**Issue by amiami5** [plonk/peercast-yt#93]
ffmpegを使用してHTTP PUSHを使用する場合のURLに
リスナー数表示の「?」を使用すると、それ以降に記載した文字列が正常に読み込まれない。

例1
http://192.168.**.**:7144/?name=ちゃんねるめい&desc=詳細&genre=tp?@@GMI&type=MKV
このように記載すると、?以降の@@やtypeが正常に認識されない。

例2
http://192.168.**.**:7144/?name=ちゃんねるめい&desc=詳細&type=MKV&genre=tp?@@GMI
genreを最後にするとtypeまでは正常に認識してくれる。

v0.1218 YT27

**Comment by plonk** [comment]
本来 `?` のようにURLで特別な意味を持つ文字はエスケープされるべきなのですが、そのまま書けたら便利なので読み込むようにします。https://github.com/plonk/peercast-yt/commit/413f3be80a0267b5f95f31cde33a6f46016ee972

さしあたって、`?` のコードは16進で `3F` なので `genre=tp%3F@@GMI` のように % 記法でエスケープしてください。

**Comment by amiami5** [comment]
ありがとうございます。お手数をおかけしました。
