### ISSUE TITLE
CLOSE_WAIT状態のTCPソケットが残る（Windows版）

### ISSUE THREAD

**Issue by koubaikoukahou** [plonk/peercast-yt#96]
長時間起動中にnetstatで確認したところ、リモートポート80番へのCLOSE_WAIT状態のソケットが大量に残っていました。

推定原因
・[uptest.cpp] download()、postRandomData()
・[chandir.cpp] getFeed()
ソケットをclose()していない。

・[wsocket.h] WSAClientSocketクラス
デストラクタ内でclose()するように定義されていない。

[uptest.cpp]でDefer cb([=] { delete rsock; });としていること及び[chandir.cpp]でunique_ptrを使用していることから、デストラクタ内でclose()するのが本来意図した動作と推察します。

なお、[usocket.h]のUClientSocketクラス（Unix系用）ではデストラクタ内でclose()しています。

**Comment by plonk** [comment]
詳細なご報告ありがとうございます。確かにMINGW版YT27でCLOSE_WAIT状態のソケットが増える現象が確認できました。

https://github.com/plonk/peercast-yt/commit/e3049d4021f71a503ab3b758a22b0a5b5964f83e で修正をコミットしました。
